### ISSUE TITLE
Landing Responsive Checks

### ISSUE THREAD

**Issue by Spit-ball** [KaeliDalton/com6338-10-10-dalton-snydersohl-flores#11]
Make sure landing page is responsive using CSS

Acceptance Criteria (AC):
- [x] Ensure elements display properly on tablet screens
- [x] Ensure elements display properly on phone screens
- [x] Create a pull request for the above requirements

**Comment by vanessa-flores4** [comment]
The landing page is responsive to ipad/tablet and phone screens.
