### ISSUE TITLE
Initial Build: Landing

### ISSUE THREAD

**Issue by Spit-ball** [KaeliDalton/com6338-10-10-dalton-snydersohl-flores#15]
Add base HTML markup and CSS styling to landing page.

Acceptance Criteria (AC):
- [x] Add basic HTML markup to index.html
- [x] Add base styling for the page to styles.css
- [x] Create a pull request for the above requirements

**Comment by vanessa-flores4** [comment]
Added landing.css for styling.

**Comment by vanessa-flores4** [comment]
Sent in a request for review.

**Comment by KaeliDalton** [comment]
I don't see any pull request to review for this
