### ISSUE TITLE
Semi-transparent Image Background

### ISSUE THREAD

**Issue by Spit-ball** [KaeliDalton/com6338-10-10-dalton-snydersohl-flores#4]
Background underneath header with related images to weather/news.

Acceptance Criteria (AC):
- [ ] Find an appropriate background photo
- [ ] Create div to hold photo and header in index.html
- [ ] Add photo file source to index.html
- [ ] Resize photo in index.html
- [ ] Add alt text for photo in index.html
- [ ] Add CSS Styling to styles.css for positioning
- [ ] Add CSS styling to styles.css for transparency
- [ ] Create a pull request for the above requirements

**Comment by vanessa-flores4** [comment]
The landing page looked cleaner without an image in the background,  I just added a background color.
