### ISSUE TITLE
News Search Bar

### ISSUE THREAD

**Issue by Spit-ball** [KaeliDalton/com6338-10-10-dalton-snydersohl-flores#5]
News Search Bar for Keywords/Titles and topics.

Acceptance Criteria
- [x] Create form in news.html
- [x] Add input in news.html
- [x] Add label in news.html
- [x] Add submit/search button in news.html
- [ ] Add form onsubmit functionality in js
- [x] Add any necessary styling for search bar into styles.css
- [x] Create a pull request for the above requirements

**Comment by saifgehlot07** [comment]
can you provide the topic of the web page you provided

**Comment by saifgehlot07** [comment]
in the folder there is only index.html, where is the news.html should i make new file.

**Comment by Spit-ball** [comment]
Form created -- JS func to come later with API data integration
